// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceRoomRevisionReducer from "../advance_room_revision_reducer";
import ClaimIdeaReducer from "../claim_idea_reducer";
import CommitIdeaReducer from "../commit_idea_reducer";
import EnqueueIdeaReducer from "../enqueue_idea_reducer";
import GrantRoomReducer from "../grant_room_reducer";
import PublishBoardReducer from "../publish_board_reducer";
import RetryIdeaReducer from "../retry_idea_reducer";
import RevokeRoomReducer from "../revoke_room_reducer";

export type AdvanceRoomRevisionParams = __Infer<typeof AdvanceRoomRevisionReducer>;
export type ClaimIdeaParams = __Infer<typeof ClaimIdeaReducer>;
export type CommitIdeaParams = __Infer<typeof CommitIdeaReducer>;
export type EnqueueIdeaParams = __Infer<typeof EnqueueIdeaReducer>;
export type GrantRoomParams = __Infer<typeof GrantRoomReducer>;
export type PublishBoardParams = __Infer<typeof PublishBoardReducer>;
export type RetryIdeaParams = __Infer<typeof RetryIdeaReducer>;
export type RevokeRoomParams = __Infer<typeof RevokeRoomReducer>;

