// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  requestId: __t.string().name("request_id"),
  operation: __t.string(),
  inputRevision: __t.u64().name("input_revision"),
  authorizationRevision: __t.u64().name("authorization_revision"),
  requestHash: __t.string().name("request_hash"),
  requestJson: __t.string().name("request_json"),
  status: __t.string(),
  responseJson: __t.string().name("response_json"),
  claimant: __t.option(__t.identity()),
  attemptId: __t.string().name("attempt_id"),
  leaseUntil: __t.u64().name("lease_until"),
});
