// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const IdeaGrant = __t.object("IdeaGrant", {
  key: __t.string(),
  roomId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
});
export type IdeaGrant = __Infer<typeof IdeaGrant>;

export const IdeaJob = __t.object("IdeaJob", {
  key: __t.string(),
  roomId: __t.string(),
  requestId: __t.string(),
  operation: __t.string(),
  inputRevision: __t.u64(),
  authorizationRevision: __t.u64(),
  requestHash: __t.string(),
  requestJson: __t.string(),
  status: __t.string(),
  responseJson: __t.string(),
  claimant: __t.option(__t.identity()),
  attemptId: __t.string(),
  leaseUntil: __t.u64(),
});
export type IdeaJob = __Infer<typeof IdeaJob>;

export const IdeaOwner = __t.object("IdeaOwner", {
  key: __t.string(),
  identity: __t.identity(),
});
export type IdeaOwner = __Infer<typeof IdeaOwner>;

export const IdeaRoomRevision = __t.object("IdeaRoomRevision", {
  roomId: __t.string(),
  inputRevision: __t.u64(),
  authorizationRevision: __t.u64(),
});
export type IdeaRoomRevision = __Infer<typeof IdeaRoomRevision>;

export const MyIdeaJobs = __t.object("MyIdeaJobs", {});
export type MyIdeaJobs = __Infer<typeof MyIdeaJobs>;

export const MyWorkflowBoards = __t.object("MyWorkflowBoards", {});
export type MyWorkflowBoards = __Infer<typeof MyWorkflowBoards>;

export const WorkflowBoard = __t.object("WorkflowBoard", {
  roomId: __t.string(),
  revision: __t.u64(),
  snapshotJson: __t.string(),
});
export type WorkflowBoard = __Infer<typeof WorkflowBoard>;

