import { pathToFileURL } from 'node:url';
import { fixture } from './fixtures.mjs';
import { createOfflineRuntime, finalMessage, callTools } from './offline.mjs';
import { runIdea } from './service.mjs';

export async function runDemo({ research = true, revise = false } = {}) {
  const operation = revise ? 'idea.revise' : 'idea.generate';
  const { request, response } = fixture(operation, { research });
  const data = structuredClone(response.data);
  const steps = research ? [callTools([
    ['search_reddit', { query: 'hackathon team choosing project disagreements' }],
    ['search_devpost', { query: 'team decision making project' }],
  ]), context => {
    const results = context.messages.filter(m => m.role === 'toolResult');
    const text = results.map(m => m.content.filter(c => c.type === 'text').map(c => c.text).join('')).join('\n');
    // Evidence keys are generated by real tool code, never invented by the fake model.
    const keys = [...text.matchAll(/"evidence_key"\s*:\s*"([^"]+)"/g)].map(m => m[1]);
    const drafts = revise ? [data.draft] : data.candidates.map(c => c.draft);
    for (const draft of drafts) draft.inspiration_refs = keys.length ? [{ evidence_key: keys[0],
      borrowed_mechanism: 'OFFLINE MOCK: explicit decision checkpoints',
      adaptation: 'Tie checkpoints to this team’s shared constraints.',
      known_difference: 'Only a fabricated demonstration; comparison has not been verified.' }] : [];
    return finalMessage(data);
  }] : [finalMessage(data)];
  const searchProvider = async ({ domains }) => [{
    url: domains?.[0] === 'reddit.com' ? 'https://www.reddit.com/r/hackathon/comments/offline/mock/' : 'https://devpost.com/software/offline-mock',
    title: 'OFFLINE MOCK — fabricated search example',
    content: 'OFFLINE MOCK: A team used human decision checkpoints. This is not a real search result.',
  }];
  return runIdea({ request, runtime: createOfflineRuntime(steps), searchProvider });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const response = await runDemo({ research: !process.argv.includes('--no-research'), revise: process.argv.includes('--revise') });
  process.stdout.write(`${JSON.stringify(response, null, 2)}\n`);
  if (response.status === 'error') process.exitCode = 1;
}
